name: alias
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  circular_countdown_timer: ^0.2.3
  confetti: ^0.7.0
  drop_shadow_image: ^0.9.1
  flutter:
    sdk: flutter
  flutter_card_swiper: ^7.0.0
  flutter_multi_select_items: ^0.4.2
  flutter_riverpod: ^2.4.9
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  shared_preferences: ^2.2.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true



  assets:
    - assets/images/
  
  fonts:
    - family: Anonymous
      fonts:
        - asset: fonts/AnonymousPro-Regular.ttf
        - asset: fonts/AnonymousPro-Bold.ttf
          weight: 700
        - asset: fonts/AnonymousPro-BoldItalic.ttf
          style: italic
       
    