name: alias
description: A new Flutter project.
publish_to: "none"
version: 0.3.2+3

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  circular_countdown_timer: ^0.2.4
  confetti: ^0.7.0
  drop_shadow_image: ^0.9.1
  flutter:
    sdk: flutter
  flutter_card_swiper: ^7.0.0

  flutter_localizations:
    sdk: flutter
  flutter_multi_select_items: ^0.4.2
  flutter_native_splash: ^2.3.7
  flutter_riverpod: ^2.4.9
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9

  intl: any
  shared_preferences: ^2.2.2
  typewritertext: ^3.0.9
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.14.1"
  freezed_annotation: ^2.4.4
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  freezed: ^2.5.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Anonymous
      fonts:
        - asset: fonts/AnonymousPro-Regular.ttf
          weight: 500
        - asset: fonts/AnonymousPro-Bold.ttf
          weight: 700
        - asset: fonts/AnonymousPro-BoldItalic.ttf
          style: italic
  generate: true
