// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIRvPahZl3RxL4K0HYzGwhZ8L4Xs3QxOo',
    appId: '1:771910261920:web:a5413cad38946272dbfdc5',
    messagingSenderId: '771910261920',
    projectId: 'alias-7aba6',
    authDomain: 'alias-7aba6.firebaseapp.com',
    storageBucket: 'alias-7aba6.firebasestorage.app',
    measurementId: 'G-4C8SWJZMKR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7p8nIn7afyMJtoLMneawsgbWvQh2jfV0',
    appId: '1:771910261920:android:eb0f807fc2bdd837dbfdc5',
    messagingSenderId: '771910261920',
    projectId: 'alias-7aba6',
    storageBucket: 'alias-7aba6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD35ld9gSo2u19NqVY3Knhe1-caiOp-Uvo',
    appId: '1:771910261920:ios:4d1a270a1a1b49b5dbfdc5',
    messagingSenderId: '771910261920',
    projectId: 'alias-7aba6',
    storageBucket: 'alias-7aba6.firebasestorage.app',
    iosBundleId: 'com.mika.alias',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD35ld9gSo2u19NqVY3Knhe1-caiOp-Uvo',
    appId: '1:771910261920:ios:491d394d7d136462dbfdc5',
    messagingSenderId: '771910261920',
    projectId: 'alias-7aba6',
    storageBucket: 'alias-7aba6.firebasestorage.app',
    iosBundleId: 'com.example.alias',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIRvPahZl3RxL4K0HYzGwhZ8L4Xs3QxOo',
    appId: '1:771910261920:web:4981db9dfb7a6199dbfdc5',
    messagingSenderId: '771910261920',
    projectId: 'alias-7aba6',
    authDomain: 'alias-7aba6.firebaseapp.com',
    storageBucket: 'alias-7aba6.firebasestorage.app',
    measurementId: 'G-1W3MM4KT1M',
  );
}
