const List<String> basic = [
  "man",
  "history",
  "pain",
  "flower",
  "ball",
  "woodman",
  "book",
  "window",
  "kettle",
  "sun",
  "star",
  "city",
  "bird",
  "apple",
  "mountain",
  "pond",
  "cloud",
  "lake",
  "candy",
  "picture",
  "tractor",
  "planet",
  "quarter",
  "river",
  "notebook",
  "square",
  "tunnel",
  "chair",
  "bulb",
  "film",
  "sock",
  "snowman",
  "cow",
  "computer",
  "cookies",
  "phone",
  "guitar",
  "coat",
  "potato",
  "family",
  "boot",
  "calendar",
  "jacket",
  "magazine",
  "umbrella",
  "nut",
  "grain",
  "bed",
  "pumpkin",
  "boot",
  "notebook",
  "bear",
  "doll",
  "wheel",
  "textbook",
  "jam",
  "wardrobe",
  "ladder",
  "lock",
  "pencil",
  "branch",
  "wind",
  "mirror",
  "blind",
  "loaf",
  "key",
  "basin",
  "basket",
  "grape",
  "candle",
  "button",
  "plate",
  "football",
  "wardrobe",
  "boat",
  "envelope",
  "broom",
  "air",
  "merry",
  "tale",
  "giant",
  "cucumber",
  "bench",
  "lantern",
  "boiler",
  "seed",
  "carrot",
  "piano",
  "pot",
  "syrup",
  "sail",
  "story",
  "mask",
  "mattress",
  "napkin",
  "backpack",
  "tulip",
  "rake",
  "rose",
  "floor",
  "hat",
  "dawn",
  "bead",
  "brick",
  "giraffe",
  "ax",
  "toothpick",
  "waste",
  "plate",
  "bill",
  "whistle",
  "flute",
  "latch",
  "saw",
  "dress",
  "office",
  "chocolate",
  "snowflake",
  "compass",
  "smile",
  "ink",
  "wreath",
  "peanut",
  "blanket",
  "house",
  "palette",
  "bagel",
  "postcard",
  "bonfire",
  "poster",
  "net",
  "festival",
  "peppercorn",
  "shoe",
  "pen",
  "landscape",
  "frog",
  "camp",
  "filler",
  "ladybug",
  "boulder",
  "blade",
  "syringe",
  "well",
  "cake",
  "collar",
  "roulette",
  "ice",
  "tree",
  "lead",
  "stove",
  "magnet",
  "pin",
  "bulb",
  "salt",
  "candlestick",
  "portfolio",
  "pearl",
  "holder",
  "curtain",
  "jellyfish",
  "pendulum",
  "comics",
  "run",
  "delicious",
  "sturdy",
  "hot",
  "fast",
  "blue",
  "soft",
  "high",
  "bright",
  "quietly",
  "simply",
  "soft",
  "acutely",
  "wise",
  "smoothly",
  "boldly",
  "fresh",
  "deep",
  "weakly",
  "direct",
  "wet",
  "free",
  "loud",
  "green",
  "dark",
  "agile",
  "purely",
  "hard",
  "dry",
  "fun",
  "short",
  "hungry",
  "perfectly",
  "widely",
  "small",
  "anxiously",
  "sweet",
  "light",
  "carefully",
  "long",
  "firm",
  "difficult",
  "hard",
  "noisily",
  "close",
  "bright",
  "carefully",
  "safely",
  "tiny",
  "hospitably",
  "successfully",
  "wonderingly",
  "steeply",
  "rough",
  "clear",
  "snug",
  "beautiful",
  "playfully",
  "fiercely",
  "fast",
  "reasonably",
  "ridiculously",
  "angrily",
  "hot",
  "lazy",
  "strongly",
  "quietly",
  "proudly",
  "cold",
  "amazingly",
  "joyfully",
  "blurred",
  "comfortable",
  "salt",
  "magical",
  "glad",
  "carefully",
  "teasing",
  "proud",
  "dizzily",
  "seriously",
  "skeptical",
  "thin",
  "terribly",
  "silly",
  "boring",
  "dreamy",
  "exciting",
  "confidently",
  "exactly",
  "firmly",
  "round",
  "acute",
  "yellow",
  "winter",
  "solar",
  "variable",
  "beautiful",
  "unfamiliar",
  "long",
  "light",
  "cozy",
  "windy",
  "cheerful",
  "alarming",
  "misty",
  "boundless",
  "elderly",
  "cloudy",
  "strong",
  "deep",
  "diverse",
  "brilliant",
  "fragile",
  "boisterous",
  "healthy",
  "excellent",
  "autumn",
  "hot",
  "frosty",
  "secret",
  "angry",
  "spring",
  "bemused",
  "exciting",
  "limitless",
  "bold",
  "flowering",
  "captivating",
  "restrained",
  "cunning",
  "amazing",
  "exciting",
  "unexpected",
  "complex",
  "impeccable",
  "strange",
  "desperate",
  "colorful",
  "unique",
  "air",
  "boy",
  "girl",
  "code",
  "folder",
  "pit",
  "dish",
  "ball",
  "forehead",
  "puddle",
  "feel",
  "give",
  "hold",
  "take away",
  "refuse",
  "indifference",
  "better",
  "delusion",
  "ask",
  "sister",
  "hear",
  "miracle",
  "look",
  "dark",
  "end",
  "sober",
  "stars",
  "song",
  "chamomile",
  "indifferently",
  "teach",
  "field",
  "birdie",
  "cigarette",
  "iron",
  "humanity",
  "oven",
  "heart",
  "cold",
  "third",
  "youth",
  "screw",
  "headphone",
  "nerve",
  "palms",
  "offender",
  "confused",
  "wander",
  "your",
  "understand",
  "kiss",
  "state",
  "neglect",
  "showcase",
  "disappear",
  "long",
  "Christmas",
  "sleep",
  "jungle",
  "wine",
  "love",
  "mountains",
  "medicine",
  "Why",
  "joy",
  "quieter",
  "movie",
  "sand",
  "screen",
  "scene",
  "scent",
  "sound",
  "charming",
  "extraordinary",
  "feeling",
  "dream",
  "memory",
  "frankly",
  "clearly",
  "quietly",
  "breath",
  "breath",
  "fire",
  "face",
  "expression",
  "clasp",
  "shoulder",
  "hand",
  "gestures",
  "view",
  "quickly",
  "slow",
  "wisdom",
  "knowledge",
  "task",
  "goal",
  "achievement",
  "success",
  "victory",
  "defeat",
  "disappointment",
  "doubt",
  "power",
  "weakness",
  "courage",
  "fear",
  "horror",
  "anxiety",
  "insult",
  "hatred",
  "kindness",
  "mercy",
  "harmony",
  "friendship",
  "love",
  "compassion",
  "soul",
  "fate",
  "destiny",
  "inspiration",
  "art",
  "art",
  "music",
  "painting",
  "literature",
  "poetry",
  "conversation",
  "dialogue",
  "singing",
  "rhythm",
  "dance",
  "the play",
  "theatrical",
  "expression",
  "light",
  "shadow",
  "contrast",
  "silhouette",
  "beam",
  "rainbow",
  "color",
  "shade",
  "reflection",
  "strip",
  "brush",
  "canvas",
  "marble",
  "stone",
  "clay",
  "glass",
  "metal",
  "tree",
  "paper",
  "artist",
  "sculptor",
  "actor",
  "writer",
  "composer",
  "director",
  "photographer",
  "musician",
  "singer",
  "dancer",
  "ballerina",
  "soloist",
  "ensemble",
  "orchestra",
  "symphony",
  "melody",
  "variety",
  "generalization",
  "comparison",
  "search",
  "discovery",
  "assumption",
  "hypothesis",
  "law",
  "theory",
  "experiment",
  "fact",
  "research",
  "information",
  "data",
  "observation",
  "explanation",
  "foresight",
  "question",
  "respond",
  "conclusion",
  "result",
  "analytics",
  "method",
  "system",
  "scheme",
  "model",
  "structure",
  "order",
  "level",
  "function",
  "algorithm",
  "program",
  "development",
  "strategy",
  "management",
  "decision",
  "coordination",
  "leadership",
  "CONTROL",
  "rating",
  "report",
  "document",
  "contract",
  "contract",
  "agreement",
  "payment",
  "score",
  "invoice",
  "bank",
  "operation",
  "deposit",
  "credit",
  "mortgage",
  "budget",
  "finances",
  "profit",
  "loss",
  "income",
  "costs",
  "investment",
  "capital",
  "tax",
  "tariff",
  "pension",
  "salary",
  "money",
  "currency",
  "bill",
  "coin",
  "business",
  "enterprise",
  "firm",
  "company",
  "organization",
  "project",
  "plan",
  "manager",
  "director",
  "executive",
  "position",
  "employee",
  "colleague",
  "subordinate",
  "head",
  "client",
  "consumer",
  "buyer",
  "seller",
  "customer",
  "provider",
  "partner",
  "competitor",
  "market",
  "product",
  "goods",
  "service",
  "discount",
  "action",
  "advertising",
  "marketing",
  "brand",
  "logotype",
  "image",
  "reputation",
  "distributor",
  "supply",
  "composition",
  "stock",
  "packaging",
  "packaging",
  "export",
  "imports",
  "Customs",
  "transport",
  "transportation",
  "delivery",
  "logistics",
  "cargo",
  "container",
  "terminal",
  "truck",
  "plane",
  "steamer",
  "ship",
  "ferry",
  "tram",
  "trolleybus",
  "underground",
  "elevator",
  "escalator",
  "platform",
  "platform",
  "rails",
  "barrier",
  "relocation",
  "stop",
  "passenger",
  "ticket",
  "ticket",
  "cashier",
  "conductor",
  "espresso",
  "route",
  "bus",
  "train",
  "propeller",
  "helicopter",
  "motorcycle",
  "bicycle",
  "scooter",
  "scooter",
  "motor scooter",
  "car",
  "service",
  "repair",
  "gasoline",
  "gas station",
  "station",
  "trip",
  "travel",
  "assignment",
  "excursion",
  "tourism",
  "hotel",
  "restaurant",
  "cafe",
  "bar",
  "coffee",
  "tea",
  "juice",
  "water",
  "milk",
  "breakfast",
  "dinner",
  "dinner",
  "dessert",
  "ice cream",
  "pie",
  "cake",
  "chocolate",
  "candy",
  "drink",
  "salad",
  "soup",
  "borsch",
  "compote",
  "dumplings",
  "dumplings",
  "dishes",
  "menu",
  "order",
  "waiter",
  "preparation",
  "service",
  "banquet",
  "holiday",
  "party",
  "meeting",
  "reception",
  "invitation",
  "guests",
  "hostess",
  "gift",
  "surprise",
  "greeting",
  "wish",
  "happiness",
  "success",
  "health",
  "good",
  "day",
  "evening",
  "morning",
  "mood",
  "inspiration",
  "weekend",
  "holidays",
  "holiday",
  "light",
  "joy",
  "smile",
  "laughter",
  "warm",
  "cosiness",
  "dog",
  "cat",
  "elephant",
  "giraffe",
  "lion",
  "tiger",
  "bee",
  "butterfly",
  "turtle",
  "camel",
  "stork",
  "deer",
  "fox",
  "wolf",
  "bunny",
  "beaver",
  "hedgehog",
  "goat",
  "marten",
  "mink",
  "mole",
  "pig",
  "hamster",
  "rat",
  "mouse",
  "horse",
  "ass",
  "donkey",
  "bull",
  "antelope",
  "rabbit",
  "spider",
  "mosquito",
  "ant",
  "cockroach",
  "cock",
  "chicken",
  "turkey",
  "goose",
  "duck",
  "parrot",
  "crow",
  "dove",
  "sparrow",
  "nightingale",
  "falcon",
  "eagle",
  "pelican",
  "gull",
  "crane",
  "cormorant",
  "raven",
  "kite",
  "swallow",
  "swift",
  "raven",
  "owl",
  "flamingo",
  "penguin",
  "swan",
  // generated

  "stream",
  "chimney",
  "garden",
  "pillow",
  "cottage",
  "road",
  "fence",
  "field",
  "bicycle",
  "shell",
  "meadow",
  "lighthouse",
  "carpet",
  "basketball",
  "crayon",
  "lantern",
  "spoon",
  "fork",
  "plate",
  "bottle",
  "box",
  "puddle",
  "forest",
  "valley",
  "cave",
  "island",
  "rope",
  "ladder",
  "bowl",
  "stool",
  "brush",
  "towel",
  "drum",
  "flask",
  "horn",
  "bridge",
  "tower",
  "ceiling",
  "curtain",
  "bookcase",
  "clock",
  "closet",
  "rug",
  "fan",
  "shovel",
  "bucket",
  "keyhole",
  "knob",
  "lever",
  "rail",
  "gear",
  "motor",
  "engine",
  "balloon",
  "kite",
  "parachute",
  "cactus",
  "bush",
  "hedge",
  "brick",
  "cement",
  "hammer",
  "nail",
  "screwdriver",
  "paintbrush",
  "hose",
  "tank",
  "boulder",
  "pebble",
  "cobblestone",
  "scissors",
  "glue",
  "eraser",
  "ruler",
  "paperclip",
  "stapler",
  "folder",
  "binder",
  "briefcase",
  "wallet",
  "purse",
  "mirror",
  "handle",
  "chain",
  "belt",
  "shoe",
  "sandal",
  "boot",
  "slipper",
  "sock",
  "jewelry",
  "ring",
  "bracelet",
  "necklace",
  "pocket",
  "watch",
  "umbrella",
  "lantern",
  "torch",
  "candle",
  "matchstick",
  "bonfire",
  "ash",
  "coals",
  "spark",
  "flame",
  "heat",
  "frost",
  "rain",
  "hail",
  "snow",
  "storm",
  "breeze",
  "fog",
  "dew",
  "sunrise",
  "sunset",
  "twilight",
  "dusk",
  "midnight",
  "noon",
  "hour",
  "minute",
  "second",
  "week",
  "month",
  "year",
  "decade",
  "century",
  "millennium",
  "season",
  "spring",
  "summer",
  "autumn",
  "winter"
];

const List<String> expert = [
  "cosmogony",
  "interferometry",
  "barycenter",
  "relativistic physics",
  "unicycle",
  "motorway",
  "GPS",
  "customs clearance",
  "gyroscooter",
  "draft animal transport",
  "distributor",
  "valve",
  "ethics",
  "dialect",
  "heritage",
  "folklore",
  "metaphor",
  "essay",
  "reader",
  "shout",
  "frustration",
  "fragile",
  "absolute",
  "avant-garde",
  "agglomeration",
  "aggregate",
  "adequacy",
  "administration",
  "azimuth",
  "acclimatization",
  "allegory",
  "ambition",
  "amplitude",
  "analyzer",
  "anomaly",
  "antagonist",
  "apathy",
  "apotheosis",
  "aristocracy",
  "artifact",
  "asymmetry",
  "association",
  "atmosphere",
  "audience",
  "barrier",
  "abyss",
  "costume jewelry",
  "biosphere",
  "proximity",
  "brand",
  "brochure",
  "brutality",
  "builder",
  "boulevard",
  "bourgeoisie",
  "bureaucracy",
  "validation",
  "squad",
  "vegetation",
  "bill",
  "vendetta",
  "verification",
  "vision",
  "Byzantinism",
  "vinyl",
  "herald",
  "eternity",
  "volt",
  "carbon",
  "node",
  "galaxy",
  "harmony",
  "hegemony",
  "genome",
  "geography",
  "hybrid",
  "dignity",
  "absurd",
  "adaptation",
  "agony",
  "relevance",
  "analogy",
  "anarchy",
  "appeal",
  "atheist",
  "aphorism",
  "multifaceted",
  "ballad",
  "baroque",
  "unprecedented",
  "blessed",
  "bust",
  "significant",
  "barbarian",
  "thoughtful",
  "luck",
  "Venus",
  "hermit",
  "desperate",
  "vision",
  "pointer",
  "flamethrower",
  "possession",
  "resurrection",
  "know-it-all",
  "harmonic",
  "hermetic",
  "giant",
  "hyperbola",
  "hypothesis",
  "global",
  "flexible",
  "pride",
  "gravity",
  "literate",
  "Greek",
  "substantial",
  "democracy",
  "deficit",
  "diplomacy",
  "discussion",
  "distance",
  "diamond",
  "dialect",
  "doctrine",
  "perfect",
  "dramatic",
  "evolution",
  "specimen",
  "elegant",
  "elementary",
  "elite",
  "syndrome",
  "sanatorium",
  "dystopia",
  "unborn",
  "touch",
  "fight",
  "devil",
  "sonnet",
  "manifesto",
  "memoirs",
  "avoid",
  "monogamy",
  "become enraged",
  "surreal",
  "cider",
  "hormones",
  "messiah",
  "virtue",
  "wizard",
  "fortune teller",
  "crown",
  "obsessed",
  "Paris",
  "Pascal",
  "Oppenheimer",
  "Fibonacci",
  "Sapkowski",
  "review",

  // extensions
  "abstraction",
  "actualization",
  "immorality",
  "antisemitism",
  "archetype",
  "biomass",
  "bionics",
  "bulletin",
  "valency",
  "explosive",
  "evaporator",
  "hydraulics",
  "devaluation",
  "demonstration",
  "destructiveness",
  "diagnostics",
  "competence",
  "exponent",
  "impromptu",
  "expression",
  "entropy",
  "ephemeral",
  "provision",
  "exacerbation",
  "preserved",
  "inertness",
  "innovation",
  "interpretation",
  "catalyst",
  "conglomerate",
  "consistency",
  "context",
  "configuration",
  "correlation",
  "criterion",
  "conciseness",
  "legitimacy",
  "lens",
  "logarithm",
  "maximum",
  "mediator",
  "methodology",
  "mythology",
  "modernization",
  "molecule",
  "monomer",
  "blower",
  "storage",
  "incompetence",
  "justification",

  "observatory",
  "paradigm",
  "parameter",
  "interweaving",
  "predictability",
  "subconscious",
  "radical",
  "rationalism",
  "resonance",
  "reconstruction",
  "retrograde",
  "reflection",
  "segment",
  "symmetry",
  "systematization",
  "subordination",
  "terminology",
  "transformation",
  "turbulence",
  "utilization",
  "physiology",
  "philanthropy",
  "functionality",
  "chronology",
  "ecological",
  "elasticity",
  "universality",
  "correlation",
  "humanism",

  // additional moderately complex words
  "paradox",
  "contemplate",
  "metamorphosis",
  "intricate",
  "cogitate",
  "juxtapose",
  "elusive",
  "ambiguous",
  "perplexing",
  "serenity",
  "catalyst",
  "meticulous",
  "indifferent",
  "vicarious",
  "cumbersome",
  "profound",
  "exquisite",
  "incessant",
  "obvious",
  "subtle",
  "benevolent",
  "resilient",
  "sophisticated",
  "precipitate",
  "peripheral",
  "enigmatic",
  "procrastinate",
  "diligent",
  "insightful",
  "precarious",
  "tangible",
  "lucid",
  "articulate",
  "nonchalant",
  "compelling",
  "substantiate",
  "affluent",
  "imminent",
  "concur",
  "ambivalent",
  "impeccable",
  "innovative",
  "trivial",
  "conducive",
  "discreet",
  "logical",
  "coherent",
  "facilitate",
  "pertinent",
  "resonate",
  "obscure",
  "explicit",
  "relevant",
  "discrepancy",
  "intrigue",
  "spontaneous",
  "ironic",
  "inevitable",
  "cohesive",
  "incisive",
  "indispensable",
  "frivolous",
  "definitive",
  "methodical",
  "provocative",
  "exponential",
  "complicated",
  "equilibrium",
  "persuasive",
  "convoluted",
  "prolific",
  "volatile",
  "insurmountable",
  "ineffable",
  "retrospective"
];

List<String> space = [
  "cosmos",
  "universe",
  "galaxy",
  "star",
  "sun",
  "planet",
  "earth",
  "moon",
  "mars",
  "venus",
  "jupiter",
  "saturn",
  "uranus",
  "neptune",
  "mercury",
  "asteroid",
  "comet",
  "meteor",
  "meteorite",
  "constellation",
  "black hole",
  "quasar",
  "pulsar",
  "orbit",
  "gravity",
  "atmosphere",
  "vacuum",
  "telescope",
  "spaceship",
  "satellite",
  "rocket",
  "cosmonaut",
  "astronaut",
  "flight",
  "space station",
  "low Earth orbit",
  "launch",
  "landing",
  "expedition",
  "explorer",
  "supernova explosion",
  "light year",
  "outer space",
  "boundary",
  "solar system",
  "meteor shower",
  "space dust",
  "gases",
  "saturn's rings",
  "crater",
  "surface",
  "spaceport",
  "radio waves",
  "signal",
  "space probe",
  "rover",
  "scientific discovery",
  "exoplanet",
  "astronomy",
  "observation",
  "navigation",
  "planetary parade",
  "dark matter",
  "dark energy",
  "exosphere",
  "stardust",
  "aurora borealis",
  "microsatellite",
  "Hubble",
  "explosion",
  "global mission",
  "interstellar space",
  "solar wind",
  "planetarium",
  "red giant",
  "white dwarf",
  "stellar system",
  "space flight",
  "device",
  "Milky Way",
  "expansion",
  "study",
  "exploration",
  "colonization",
  "science",
  "outer space",
  "vacuum space",
  "galactic center",
  "wave",
  "spacetime continuum",
  "satellite",
  "space race",
  "odyssey",
  "black hole",
  "gravity",
  "astrophysics",
  "gravitational lens",
  "singularity",
  "spectroscopy",
  "light aberration",
  "accretion disk",
  "antiparticle",
  "redshift",
  "blueshift",
  "gravitational radiation",
  "cosmic microwave background",
  "gravitational wave",
  "astronomical unit",
  "radiation belt",
  "supernova",
  "cosmological model",
  "Doppler effect",
  "isotopic analysis",
  "stellar spectrum",
  "magnetosphere",
  "stellar cluster",
  "plasma",
  "nebula",
  "cosmic cycle",
  "ionizing radiation",
];

List<String> slang = [
  "lol",
  "lmao",
  "rofl",
  "memes",
  "troll",
  "dank",
  "pepe",
  "doge",
  "rickroll",
  "meme lord",
  "yeet",
  "fomo",
  "stan",
  "spaghetti",
  "smh",
  "bruh",
  "no cap",
  "ok boomer",
  "flex",
  "chad",
  "virgil",
  "sus",
  "vibe check",
  "lit",
  "bro",
  "karen",
  "epic",
  "wholesome",
  "yolo",
  "bet",
  "tbh",
  "roast",
  "salty",
  "savage",
  "cringe",
  "mood",
  "thirst trap",
  "clickbait",
  "dead inside",
  "cap",
  "clap back",
  "good vibes",
  "cancelled",
  "simp",
  "vibe",
  "lowkey",
  "highkey",
  "that’s a vibe",
  "big mood",
  "bruh moment",
  "pepe the frog",
  "when the squad",
  "big brain",
  "fyp",
  "cursed",
  "who asked",
  "based",
  "cheugy",
  "milk",
  "normie",
  "tik tok",
  "inspo",
  "hashtag relatable",
  "yeet",
  "its the ____ for me",
  "swole",
  "gacha",
  "glow up",
  "stonks",
  "tbh",
  "im dead",
  "catch these hands",
  "facts",
  "iconic",
  "snack",
  "woke",
  "giga chad",
  "chilling",
  "periodt",
  "shook",
  "vibe",
  "meme king",
  "stay woke",
  "real one",
  "be like",
  "cringe compilation",
  "wanna fight?",
  "yeet",
  "its lit",
  "thats fire",
  "period",
  "real talk",
  "womp womp",
  "big brain energy",
  "take the L",
  "noob",
  "stressed but blessed",
  "betch",
  "crackhead energy",
  "clown",
  "yeet or be yeeted",
  "savage mode",
  "hot take",
  "we stan",
  "mood swings",
  "i’m baby",
  "big flex",
  "tfw",
  "ayyy",
  "let’s get this bread",
  "hit different",
  "blessed",
  "slaps",
  "i’m dead",
  "died laughing",
  "periodt",
  "weird flex but ok",
  "shut up and take my money",
  "that’s cap",
  "wildin",
  "stay mad",
  "sipping tea",
  "child’s play",
  "dragging",
  "on site",
  "for real",
  "come at me",
  "catch me outside",
  "don’t @ me",
  "done with you",
  "feel that",
  "who hurt you",
  "cancel culture",
  "post and ghost",
  "okay but why",
  "i can't even",
  "mood af",
  "cringe fest",
  "not today",
  "bless your heart",
  "yeet squad",
  "boomer humor",
  "get rekt",
  "shut your mouth",
  "that’s facts",
  "wasted",
  "snatched",
  "make it make sense",
  "bet money",
  "keep it 100",
  "whole vibe",
  "triggered",
  "feelings",
  "so extra",
  "extra much",
  "your move",
  "good to go",
  "same energy",
  "fight me",
  "big mad",
  "that’s tea",
  "slay",
  "wild",
  "it be like that",
  "we don’t do that here",
  "just vibing",
  "catch these vibes",
  "hype",
  "woke af",
  "finna",
  "trending",
  "cancelled culture",
];

List<String> gamersSlang = [
  "gg",
  "noob",
  "pwned",
  "frag",
  "camping",
  "op",
  "n00b",
  "1v1",
  "clutch",
  "headshot",
  "easy",
  "tryhard",
  "afk",
  "gg ez",
  "streak",
  "loot",
  "epic win",
  "ragequit",
  "twitch",
  "streamer",
  "game mode",
  "skins",
  "playthrough",
  "grind",
  "nerf",
  "buff",
  "meta",
  "lag",
  "ping",
  "queue",
  "patch notes",
  "pro gamer",
  "casual",
  "power level",
  "respawn",
  "game over",
  "ranked",
  "xp",
  "multiplayer",
  "co-op",
  "free-to-play",
  "pay-to-win",
  "achievement unlocked",
  "boss fight",
  "level up",
  "unlockables",
  "dungeon",
  "raid",
  "guild",
  "clan",
  "build",
  "battle royale",
  "loot box",
  "skins",
  "server",
  "latency",
  "pro-gaming",
  "speedrun",
  "esports",
  "mod",
  "crossplay",
  "controller",
  "mouse",
  "keyboard",
  "camp",
  "teabag",
  "spawn trap",
  "health bar",
  "crit",
  "buff",
  "debuff",
  "tank",
  "healer",
  "damage dealer",
  "support",
  "shooter",
  "rpg",
  "fps",
  "turn-based",
  "strategy",
  "arena",
  "e-sports",
  "killstreak",
  "combo",
  "combo breaker",
  "endgame",
  "drop",
  "loot",
  "pve",
  "pvp",
  "multiplayer",
  "skins",
  "rpg",
  "mob",
  "agro",
  "grind",
  "party",
  "matchmaking",
  "tournament",
  "gg wp",
  "clutch moment",
  "meta pick",
  "hacker",
  "no-scope",
  "triple kill",
  "quad kill",
  "team wipe",
  "headshot machine",
  "ranked mode",
  "boosting",
  "matchup",
  "drop zone",
  "respawn time",
  "rank",
  "mvp",
  "killcam",
  "stream sniping",
  "beta test",
  "fps lag",
  "pvp mode",
  "solo queue",
  "duo",
  "trio",
  "noob tube",
  "damage boost",
  "streamer loot",
  "clutch or kick",
  "revive",
  "disconnect",
  "ghosting",
  "rage mode",
  "revive me",
  "camping spot",
  "kill feed",
  "deathmatch",
  "grinder",
  "power-up",
  "trick shot",
  "noobish",
  "carry",
  "2v2",
  "counter pick",
  "play to win",
  "carry me",
  "headshot only",
  "strafing",
  "competitive",
  "aggressive play",
  "tactical retreat",
  "backseat gamer",
  "gamer fuel",
  "clutch round",
  "down but not out",
  "ultimate ability",
  "pocket healer",
  "get the dub",
  "reboot van"
      "Overwatch",
  "Dota 2",
  "League of Legends",
  "Fortnite",
  "Call of Duty",
  "Valorant",
  "Minecraft",
  "Apex Legends",
  "PUBG",
  "Counter-Strike",
  "Rocket League",
  "Hearthstone",
  "World of Warcraft",
  "Red Dead Redemption 2",
  "FIFA",
  "Halo",
  "Rainbow Six Siege",
  "World of Tanks",
  "Super Smash Bros",
  "Among Us",
  "Dead by Daylight",
  "Fall Guys",
  "GTA V",
  "Zelda",
  "The Witcher 3",
  "Skyrim",
  "The Last of Us",
  "The Legend of Zelda",
  "Final Fantasy",
  "Mortal Kombat",
  "Super Mario",
  "Pokemon",
  "Star Wars",
  "Halo",
  "Rainbow Six",
  "Destiny",
  "Helldivers 2",
  "Destiny 2",
  "Gears of War",
  "Civilization 6",
  "Civilization 7",
  "Age of Empires",
  "Escape from Tarkov",
  "Modern Warfare",
  "Black Ops 4",
  "Black Ops 3",
  "The Finals",
  "The Last Of Us",
  "The Last Of Us: Part 2",
  "The Forest",
  "Star Citizen",
  "Little Nightmares",
  "Dark Souls",
  "Dark Souls 2",
  "Dark Souls 3",
  "Little Nightmares 2",
  "Hogwarts Legacy",
  "Red Dead Redemption",
  "Disco Elysium",
  "Elden Ring",
  "Cyberpunk 2077",
  "Resident Evil 2",
  "Baldur's Gate 3",
  "World of Warcraft",
  "Wolrd of Tanks",
  "Subnautica",
  "Hades 2",
  "Starfield",
  "Sekiro",
  "Far Cry 5",
  "Ghost of Tsushima",
];

List<String> it = [
  "algorithm",
  "array",
  "backend",
  "binary",
  "bit",
  "blockchain",
  "boolean",
  "bug",
  "cache",
  "class",
  "compiler",
  "component",
  "data structure",
  "database",
  "debugging",
  "deployment",
  "design pattern",
  "endpoint",
  "framework",
  "frontend",
  "function",
  "inheritance",
  "interface",
  "JavaScript",
  "library",
  "loop",
  "method",
  "module",
  "object",
  "parameter",
  "pointer",
  "programming language",
  "query",
  "React",
  "refactoring",
  "repository",
  "script",
  "server",
  "session",
  "syntax",
  "variable",
  "web design",
  "wireframe",
  "user interface",
  "user experience",
  "pixel",
  "grid system",
  "style sheet",
  "markup",
  "layout",
  "template",
  "mockup",
  "prototype",
  "style guide",
  "design system",
  "font",
  "color palette",
  "contrast",
  "typography",
  "responsive design",
  "responsive layout",
  "accessibility",
  "user flow",
  "iconography",
  "animation",
  "image compression",
  "vector graphics",
  "wireframe",
  "font size",
  "media query",
  "bootstrap",
  "CSS",
  "HTML",
  "JavaScript",
  "web development",
  "mobile development",
  "database management",
  "cloud storage",
  "server-side",
  "client-side",
  "full-stack",
  "hosting",
  "debugging tools",
  "version control",
  "git",
  "commit",
  "branch",
  "merge",
  "repository",
  "code review",
  "pair programming",
  "agile",
  "scrum",
  "Kanban",
  "frontend framework",
  "backend framework",
  "MVC",
  "codebase",
  "open-source",
  "documentation",
  "user research",
  "A/B testing",
  "wireframing tools",
  "Figma",
  "Sketch",
  "Adobe XD",
  "Photoshop",
  "Illustrator",
  "UI kit",
  "mockup",
  "animation software",
  "prototyping",
  "image editing",
  "vector graphics",
  "logo design",
  "brand identity",
  "mockup tool",
  "flowchart",
  "infographic",
  "data visualization",
  "web accessibility",
  "media queries",
  "SVG",
  "front-end",
  "back-end",
  "server",
  "database",
  "API",
  "UI design",
  "UX design",
  "interaction design",
  "visual design",
  "design thinking",
  "user testing",
  "feedback",
  "prototype",
  "cross-browser",
  "cross-platform",
  "CSS Grid",
  "Flexbox",
  "grid layout",
  "media queries",
  "serverless architecture",
  "cloud computing",
  "data security",
  "SSL",
  "encryption",
  "cloud migration",
  "cloud storage",
  "web application",
  "mobile application",
  "performance optimization",
  "load testing",
  "scalability",
  "data modeling",
  "data processing",
  "data analysis",
  "testing",
  "unit testing",
  "integration testing",
  "user acceptance testing",
  "quality assurance",
  "automation",
  "code quality",
  "debugger",
  "debugging tool",
  "profiling",
  "responsive typography",
  "input validation",
  "code efficiency",
  "refactoring",
  "concurrency",
  "multithreading",
  "data integrity",
  "database schema",
  "query optimization",
  "SQL",
  "NoSQL",
  "cloud infrastructure",
  "firewall",
  "server management",
  "data privacy",
  "compliance",
  "penetration testing",
  "ethical hacking",
  "penetration tester",
  "intrusion detection",
  "security patch",
  "vulnerability",
  "penetration test",
  "DDoS",
  "firewall rule",
  "data breach",
  "access control",
  "authentication",
  "authorization",
  "session management",
  "password hashing",
  "data encryption",
  "network security",
  "data loss prevention",
  "cloud security",
  "risk management",
  "data protection",
  "cybersecurity",
  "server security",
  "network protocols",
  "UDP",
  "TCP/IP",
  "web security",
  "HTTPS",
  "HTTP",
  "SFTP",
  "FTP",
  "IP address",
  "subnet",
  "router",
  "VPN",
  "SSH",
  "proxy server",
  "hosting service",
  "cloud platform",
  "big data",
  "machine learning",
  "data science",
  "artificial intelligence",
  "deep learning",
  "neural networks",
  "data analysis",
  "data mining",
  "data lake",
  "data warehousing",
  "data visualization",
  "predictive modeling",
  "AI algorithm",
  "model training",
  "model testing",
  "feature engineering",
  "data preprocessing",
  "reinforcement learning",
  "unsupervised learning",
  "supervised learning",
  "computer vision",
  "natural language processing",
  "chatbot",
  "voice recognition",
  "image recognition",
  "speech recognition",

  "Python",
  "Java",
  "JavaScript",
  "C",
  "C++",
  "C#",
  "Ruby",
  "PHP",
  "Swift",
  "Go",
  "Rust",
  "Kotlin",
  "TypeScript",
  "HTML",
  "CSS",
  "SQL",
  "R",
  "MATLAB",
  "Perl",
  "Lua",
  "Shell",
  "Scala",
  "Dart",
  "Objective-C",
  "Fortran",
  "Elixir",
  "Clojure",
  "F#",
  "Julia",
  "ActionScript",
  "Solidity",
  "Verilog",
  "VB.NET",
  "GDScript",
  "Rust",

  // Frameworks
  "React",
  "Vue.js",
  "Angular",
  "Node.js",
  "Django",
  "Flask",
  "Spring",
  "Laravel",
  "Express",
  "Ruby on Rails",
  "ASP.NET",
  "Bootstrap",

  "jQuery",

  "AngularJS",

  "Svelte",
  "Tailwind CSS",
  "Next.js",
  "NestJS",

  "Laravel",

  "Flutter",
  "SwiftUI",
];

List<String> popularFilms = [
  "The Shawshank Redemption",
  "The Godfather",
  "The Dark Knight",
  "Pulp Fiction",
  "The Lord of the Rings: The Return of the King",
  "Forrest Gump",
  "Inception",
  "Fight Club",
  "The Matrix",
  "The Empire Strikes Back",
  "The Godfather: Part II",
  "Goodfellas",
  "The Avengers",
  "Schindler's List",
  "Back to the Future",
  "Star Wars: A New Hope",
  "The Silence of the Lambs",
  "The Lion King",
  "Gladiator",
  "The Prestige",
  "Interstellar",
  "The Departed",
  "Jurassic Park",
  "Terminator 2: Judgment Day",
  "The Green Mile",
  "The Intouchables",
  "The Pianist",
  "Whiplash",
  "Blade Runner 2049",
  "Citizen Kane",
  "Casablanca",
  "Seven Samurai",
  "The Dark Knight Rises",
  "Avengers: Endgame",
  "The Social Network",
  "The Wolf of Wall Street",
  "The Revenant",
  "The Big Lebowski",
  "Parasite",
  "Once Upon a Time in Hollywood",
  "Mad Max: Fury Road",
  "The Matrix Reloaded",
  "The Lord of the Rings: The Fellowship of the Ring",
  "The Truman Show",
  "The Shining",
  "The Grand Budapest Hotel",
  "La La Land",
  "Spider-Man: Into the Spider-Verse",
  "Moonlight",
  "Her",
  "The Sixth Sense",
  "A Clockwork Orange",
  "12 Angry Men",
  "The Princess Bride",
  "Avatar",
  "The Witcher",
  "The Incredibles",
  "Frozen",
  "Guardians of the Galaxy",
  "Deadpool",
  "Jaws",
  "Saving Private Ryan",
  "The Exorcist",
  "Memento",
  "The Hunger Games",
  "Eternal Sunshine of the Spotless Mind",
  "The Matrix Revolutions",
  "The Incredibles 2",
  "The Nightmare Before Christmas",
  "Raging Bull",
  "The Godfather: Part III",
  "Tenet",
  "Spider-Man: No Way Home",
  "Dune",
  "Nomadland",
  "A Quiet Place",
  "Joker",
  "The Irishman",
  "Knives Out",
  "Soul",
  "Parasite",
  "Everything Everywhere All at Once",
  "The Batman",
  "Avengers: Infinity War",
  "Shang-Chi and the Legend of the Ten Rings",
  "Black Panther",
  "The Matrix Resurrections",
  "Coda",
  "Free Guy",
  "Jungle Cruise",
  "The Suicide Squad",
  "Cruella",
  "Luca",
  "The Last Duel",
  "Don't Look Up",
  "King Richard",
  "Encanto",
  "Spider-Man: Across the Spider-Verse",
  "Doctor Strange in the Multiverse of Madness",
  "Free Guy",
  "The French Dispatch",
  "Scream (2022)",
  "The Menu",
  "Black Widow",
  "Eternals",
  "No Time to Die",
  "The Lost City",
  "Ghostbusters: Afterlife",
  "Oppenheimer",
  "The Substance",
  "Spirited Away",
  "My Neighbor Totoro",
  "Akira",
  "Princess Mononoke",
  "Your Name",
  "Howl's Moving Castle",
  "The Wind Rises",
  "Grave of the Fireflies",
  "Ponyo",
  "Kiki's Delivery Service",
  "Perfect Blue",
  "Paprika",
];
