final List<String> ukTeamNames = [
  "Ми не такі божевільні",
  "Летючі мавпи",
  "Мисливці на монстрів",
  "Драйвери",
  "Немиті єноти",
  "Технічні гіганти",
  "Супер пупер чуваки",
  "Безсонні кодери",
  "Ворожі доносчики",
  "Друзі по боулінгу",
  "Анонімні алкоголики",
  "Кінгконголюби",
  "Треба танцювати, зараз!",
  "Нічого нового",
  "Дикий народ",
  "Ми проводимо цю гру",
  "Панди у рожевому",
  "От такі ми",
  "Нерозумні (тупі)",
  "Маленькі гвиньтіки",
  "Без Паші",
  "Тімур в соло",
  "Без Андрія",
  "Леви на джипі",
  "Смішні як Буданов",
  "47 iq",
  "Пишуть софт",
  "Пишуть хард, шо?",
  "Технічні терористи",
  "Жорстокі романтики",
  "Хто ми?",
  "Хто я?",
  "Живодери",
  "Дитячі бумери",
  "Вибувші з коледжу",
  "Низькі очікування",
  "Дно бочки",
  "Найслабкіші ланки",
  "Комплекс неперевершеності",
  "Щось необразливе",
  "Друге місце",
  "Перше місце",
  "Третє місце",
  "Команда 'Б'",
  "Теплі серцем",
  "Інкогніто",
  "The Chosen Ones",
  "Найгарніші",
  "Покличте коли почнете",
  "Аніме фанати",
  "Із Рівії",
];

final List<String> enTeamNames = [
  "We're Not That Crazy",
  "Flying Monkeys",
  "Monster Hunters",
  "Drivers",
  "Unwashed Raccoons",
  "Tech Giants",
  "Super Duper Guys",
  "Sleepless Coders",
  "Hostile Informers",
  "Bowling Buddies",
  "Anonymous Alcoholics",
  "King Kong Lovers",
  "Let's Dance, Now!",
  "Nothing New",
  "Wild Folks",
  "We're Running This Game",
  "Pandas in Pink",
  "That's Who We Are",
  "Dumb (Stupid)",
  "Little Screws",
  "Without Pasha",
  "Timur in Solo",
  "Without Andriy",
  "Lions in a Jeep",
  "Funny Like Budanov",
  "47 IQ",
  "Software Writers",
  "Hard Writers, What?",
  "Tech Terrorists",
  "Brutal Romantics",
  "Who Are We?",
  "Who Am I?",
  "Animal Cruelty",
  "Boomer Kids",
  "College Dropouts",
  "Low Expectations",
  "Bottom of the Barrel",
  "Weakest Links",
  "Superiority Complex",
  "Something Inoffensive",
  "Second Place",
  "First Place",
  "Third Place",
  "Team 'B'",
  "Warm-Hearted",
  "Incognito",
  "The Chosen Ones",
  "The Prettiest",
  "Call Us When You Start",
  "Anime Fans",
  "From Rivia",
];
