final List<String> ukTeamNames = [
  "Ми не такі божевільні",
  "Летючі мавпи",
  "Мисливці на монстрів",
  "Драйвери",
  "Немиті єноти",
  "Технічні гіганти",
  "Супер пупер чуваки",
  "Безсонні кодери",
  "Ворожі доносчики",
  "Друзі по боулінгу",
  "Анонімні алкоголики",
  "Кінгконголюби",
  "Треба танцювати, зараз!",
  "Нічого нового",
  "Дикий народ",
  "Ми проводимо цю гру",
  "Панди у рожевому",
  "От такі ми",
  "Нерозумні (тупі)",
  "Маленькі гвиньтіки",
  "Без Паші",
  "Тімур в соло",
  "Без Андрія",
  "Леви на джипі",
  "47 iq",
  "Пишуть софт",
  "Пишуть хард, шо?",
  "Технічні терористи",
  "Жорстокі романтики",
  "Хто ми?",
  "Хто я?",
  "Живодери",
  "Дитячі бумери",
  "Вибувші з коледжу",
  "Низькі очікування",
  "Дно бочки",
  "Найслабкіші ланки",
  "Комплекс неперевершеності",
  "Щось необразливе",
  "Друге місце",
  "Перше місце",
  "Третє місце",
  "Команда 'Б'",
  "Теплі серцем",
  "Інкогніто",
  "The Chosen Ones",
  "Найгарніші",
  "Покличте коли почнете",
  "Аніме фанати",
  "Із Рівії",
  "Команда 'А'",
  "Що ще треба дітям для щастя?",
  "Діди",
  "У розпачі",
  "Дизайнери на мендальному",
  "Читають книжки",
  "Не читають книжки",
  "Що таке книжка?",
  "Діскорд адміни",
  "Як сдатися?",
  "Не читали правила",
  "Забули правила",
];

final List<String> enTeamNames = [
  "We're Not That Crazy",
  "Flying Monkeys",
  "Monster Hunters",
  "Unwashed Raccoons",
  "Super Duper Guys",
  "Sleepless Coders",
  "Bowling Buddies",
  "Anonymous Alcoholics",
  "Let's Dance, Now!",
  "Nothing New",
  "We're Running This Game",
  "Pandas in Pink",
  "That's Who We Are",
  "Dumb (Stupid)",
  "47 IQ",
  "Tech Terrorists",
  "Brutal Romantics",
  "College Dropouts",
  "Low Expectations",
  "Weakest Links",
  "Superiority Complex",
  "Something Inoffensive",
  "Second Place",
  "First Place",
  "Third Place",
  "Warm-Hearted",
  "Incognito",
  "The Chosen Ones",
  "The Prettiest",
  "Call Us When You Start",
  "Anime Fans",
  "From Rivia",
];
